server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple-video?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    template-loader-path: classpath:/templates/


# Sa-Token-Quick-Login 配置
sa:
  # 登录账号
  name: sa
  # 登录密码
  pwd: 123456
  # 是否自动随机生成账号密码 (此项为true时, name与pwd失效)
  auto: false
  # 是否开启全局认证(关闭后将不再强行拦截)
  auth: true
  # 登录页标题
  title: Sa-Token 登录
  # 是否显示底部版权信息
  copr: true
  # 指定拦截路径
  # include: /**
  # 指定排除路径
  # exclude: /1.jpg
  # 将本地磁盘的某个路径作为静态资源开放
  # dir: file:E:\static

# Minio配置
minio:
  url: http://localhost:9000/
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: assets
